version: '3.9'

networks:
  nginx:
    name: 'nginx'
    external: true

services:
  api:
    build:
      context: .
      dockerfile: cmd/api/Dockerfile
    container_name: api
    restart: always
    networks:
      - nginx
    environment:
      APP_DEBUG: "${APP_DEBUG:?}"
      APP_BUN_DEBUG: "${APP_BUN_DEBUG:?}"
      APP_JWT_PATH: "${APP_JWT_PATH:?}"
      POSTGRES_USER: "${POSTGRES_USER:?}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:?}"
      POSTGRES_HOST: "${POSTGRES_HOST:?}"
      POSTGRES_PORT: "${POSTGRES_PORT:?}"
      POSTGRES_DB: "${POSTGRES_DB:?}"
      POSTGRES_CERT_PATH: "${POSTGRES_CERT_PATH:?}"
    logging:
      driver: json-file
      options:
        max-size: 4m
        max-file: "1"
        tag: api
